### ISSUE TITLE
期待最新的论文代码开源

### ISSUE THREAD

**Issue by TaylorRex** [MrGiovanni/SyntheticTumors#11]
拜读了您最新的肿瘤生成论文，不知最新的论文代码何时开源，很想跟进学习！感谢您做出的卓越贡献！

**Comment by MrGiovanni** [comment]
Hi @TaylorRex 

Thanks for your message. The code for our new paper—I assume you meant ([Q. Chen et al. CVPR 2024](https://www.cs.jhu.edu/~alanlab/Pubs24/chen2024towards.pdf))—will be released before Mar 15, 2024.

This will be the link: https://github.com/MrGiovanni/DiffTumor

Best,
Zongwei
