### ISSUE TITLE
Can you update file inference ?

### ISSUE THREAD

**Issue by nam157** [MrGiovanni/SyntheticTumors#5]
I want to run file single .nii. So, I think a file inference for this project. Can you update ?

**Comment by qixinhu11** [comment]
Thanks for your interest in this paper, sorry for the late reply.
I will add this feature when I get some free time. 
As you can see from the validation.py, the core part is already been written. If you are familiar with the MONAI framework, you can write your version.  But if you don't want to change the source code, I suggest you write a new JSON file with a single item and then run the validation.py.
Hope this could help you.
